import { Request, Response } from "express";
import { prisma } from "../db";
import { quotationSchema, statusSchema } from "../utils/validation";
import { AuthUser } from "../middleware/auth";
import { idParam, roundMoney, HttpError } from "../utils/http";
const number = () => `QUO-${Date.now().toString().slice(-8)}`;
export async function listQuotations(_req: Request, res: Response) { res.json({ success: true, data: await prisma.quotation.findMany({ include: { customer: true, enquiry: true, items: { include: { product: true } }, order: true }, orderBy: { createdAt: "desc" } }) }); }
export async function createQuotation(req: Request, res: Response) { const input = quotationSchema.parse(req.body); const enquiry = await prisma.enquiry.findUnique({ where: { id: input.enquiryId } }); if (!enquiry) throw new HttpError(404, "Enquiry not found"); const calculated = input.items.map(item => { const base = item.quantity * item.unitPrice; const afterDiscount = base * (1 - item.discountPct / 100); const lineAmount = roundMoney(afterDiscount * (1 + item.taxPct / 100)); return { ...item, lineAmount }; }); const subtotal = roundMoney(calculated.reduce((sum, item) => sum + item.quantity * item.unitPrice * (1 - item.discountPct / 100), 0)); const tax = roundMoney(calculated.reduce((sum, item) => sum + item.lineAmount - item.quantity * item.unitPrice * (1 - item.discountPct / 100), 0)); const total = roundMoney(subtotal + tax); const data = await prisma.quotation.create({ data: { quotationNo: number(), enquiryId: input.enquiryId, customerId: enquiry.customerId, createdById: (res.locals.user as AuthUser).userId, validUntil: input.validUntil ? new Date(input.validUntil) : undefined, subtotal, discount: roundMoney(input.items.reduce((sum, i) => sum + i.quantity * i.unitPrice * i.discountPct / 100, 0)), tax, total, items: { create: calculated } }, include: { customer: true, items: { include: { product: true } } } }); await prisma.enquiry.update({ where: { id: enquiry.id }, data: { status: "QUOTED" } }); res.status(201).json({ success: true, data }); }
export async function updateQuotationStatus(req: Request, res: Response) { const input = statusSchema.parse(req.body); if (!["DRAFT", "SENT", "ACCEPTED", "REJECTED"].includes(input.status)) throw new HttpError(400, "Invalid quotation status"); const data = await prisma.quotation.update({ where: { id: idParam(req.params.id) }, data: { status: input.status as any } }); res.json({ success: true, data }); }
