import React, { useEffect, useState } from "react";
import api from "../services/api";
const money = (value) => `₹${Number(value ?? 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const message = (error) => error.response?.data?.message || "Unable to complete action";
function Modal({ onClose, children }) { return <div className="modal-backdrop"><section className="modal"><button className="close" onClick={onClose}>×</button>{children}</section></div>; }
export default function Quotations() {
  const [rows, setRows] = useState([]); const [enquiries, setEnquiries] = useState([]); const [products, setProducts] = useState([]); const [show, setShow] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ enquiryId: "", productId: "", quantity: 1, unitPrice: 0, discountPct: 0, taxPct: 18 });
  const load = async () => { const [q, e, p] = await Promise.all([api.get("/quotations"), api.get("/enquiries"), api.get("/products")]); setRows(q.data.data); setEnquiries(e.data.data.filter((item) => item.status !== "LOST")); setProducts(p.data.data); };
  useEffect(() => { load().catch(() => {}); }, []);
  const update = (field, value) => { const next = { ...form, [field]: value }; if (field === "productId") { const product = products.find((item) => item.id === Number(value)); next.unitPrice = product ? Number(product.basePrice) : 0; } setForm(next); };
  const create = async (event) => { event.preventDefault(); try { await api.post("/quotations", { enquiryId: Number(form.enquiryId), items: [{ productId: Number(form.productId), quantity: Number(form.quantity), unitPrice: Number(form.unitPrice), discountPct: Number(form.discountPct), taxPct: Number(form.taxPct) }] }); setShow(false); setForm({ enquiryId: "", productId: "", quantity: 1, unitPrice: 0, discountPct: 0, taxPct: 18 }); load(); } catch (err) { setError(message(err)); } };
  const status = async (id, value) => { await api.patch(`/quotations/${id}/status`, { status: value }); load(); };
  const convert = async (id) => { try { await api.post(`/orders/from-quotation/${id}`); load(); } catch (err) { setError(message(err)); } };
  return <><header className="page-header"><div><span className="eyebrow">02 / COMMERCIAL RESPONSE</span><h1>Quotations</h1></div><button className="primary" onClick={() => setShow(true)}>New quotation <span>＋</span></button></header><section className="table-card"><div className="table-title"><div><span className="eyebrow">QUOTATION REGISTER</span><h2>Commercial proposals</h2></div><span className="count">{rows.length} records</span></div>{error && <div className="alert">{error}</div>}{rows.length ? <table><thead><tr><th>Reference</th><th>Customer</th><th>Value</th><th>Valid until</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className="mono">{row.quotationNo}<small>{row.enquiry.enquiryNo}</small></td><td>{row.customer.companyName}</td><td><strong>{money(row.total)}</strong><small>Subtotal {money(row.subtotal)} · GST {money(row.tax)}</small></td><td>{row.validUntil ? new Date(row.validUntil).toLocaleDateString() : "—"}</td><td><span className={`pill ${row.status.toLowerCase()}`}>{row.status}</span></td><td>{row.status === "DRAFT" && <button className="text-button" onClick={() => status(row.id, "SENT")}>Send →</button>}{row.status === "SENT" && <><button className="text-button" onClick={() => status(row.id, "ACCEPTED")}>Accept</button><button className="text-button danger" onClick={() => status(row.id, "REJECTED")}>Reject</button></>}{row.status === "ACCEPTED" && !row.order && <button className="text-button" onClick={() => convert(row.id)}>Create order →</button>}</td></tr>)}</tbody></table> : <div className="empty"><span>◎</span><p>No quotations yet. Price an enquiry to begin.</p></div>}</section>{show && <Modal onClose={() => setShow(false)}><span className="eyebrow">WORKSPACE ACTION</span><h2>Price an enquiry</h2><form onSubmit={create} className="form-grid"><label>Enquiry<select required value={form.enquiryId} onChange={(e) => update("enquiryId", e.target.value)}><option value="">Choose enquiry</option>{enquiries.map((item) => <option key={item.id} value={item.id}>{item.enquiryNo} · {item.customer.companyName}</option>)}</select></label><label>Product<select required value={form.productId} onChange={(e) => update("productId", e.target.value)}><option value="">Choose product</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Quantity<input type="number" min="1" value={form.quantity} onChange={(e) => update("quantity", e.target.value)} /></label><label>Unit price<input type="number" min="0" value={form.unitPrice} onChange={(e) => update("unitPrice", e.target.value)} /></label><label>Discount %<input type="number" min="0" max="100" value={form.discountPct} onChange={(e) => update("discountPct", e.target.value)} /></label><label>GST %<input type="number" min="0" max="100" value={form.taxPct} onChange={(e) => update("taxPct", e.target.value)} /></label><button className="primary full">Create draft quotation</button></form></Modal>}</>;
}
